# Generated by Django 4.2.3 on 2023-07-20 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_elevator_request_delete_log'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elevator_request',
            new_name='ElevatorRequest',
        ),
    ]
