# Generated by Django 4.2.3 on 2023-07-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_elevator_is_available_alter_elevator_elevator_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevatorrequest',
            name='elevator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elevator_logs', to='myapp.elevator'),
        ),
    ]
