# Generated by Django 4.2.3 on 2023-07-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_elevatorrequest_next_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='is_door_open',
            field=models.BooleanField(default=True),
        ),
    ]
